In [4]:
import pandas as pd

pbp_2020 = pd.read_parquet ( "data/raw/play_by_play_2020.parquet")

pbp_2020.head()

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,None,None,None,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,1.294838,0.50337,4.275047,2.0,0.619306,0.239695,0.515058,48.494154
3,93.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,0.857214,NaN,NaN,NaN,NaN,NaN,0.413357,-41.335732
4,118.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,-0.454665,NaN,NaN,NaN,NaN,NaN,0.446920,-44.692025

In [7]:
import pandas as pd
import glob

files = glob.glob( "data/raw/play_by_play_*.parquet")

pbp_all = pd.concat ([pd.read_parquet(f) for f in files], ignore_index=True)

print( "Combined dataset shape:", pbp_all.shape)
pbp_all.head()

Combined dataset shape: (254491, 372)

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,None,None,None,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,1.294838,0.50337,4.275047,2.0,0.619306,0.239695,0.515058,48.494154
3,93.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,0.857214,NaN,NaN,NaN,NaN,NaN,0.413357,-41.335732
4,118.0,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0.0,1.0,-0.454665,NaN,NaN,NaN,NaN,NaN,0.446920,-44.692025

In [9]:
print( "Rows, Columns:", pbp_all.shape)

pbp_all.head()

pbp_all.tail()

Rows, Columns: (254491, 372)

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
254486,4017.0,2025_03_PIT_NE,2025092104,NE,PIT,REG,3,None,None,None,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254487,4005.0,2025_03_PIT_NE,2025092104,NE,PIT,REG,3,NE,home,PIT,...,0.0,1.0,-1.992871,3.639289,6.729582,5.0,0.825747,0.825747,0.7334,26.660037
254488,4037.0,2025_03_PIT_NE,2025092104,NE,PIT,REG,3,PIT,away,NE,...,0.0,1.0,-0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254489,4059.0,2025_03_PIT_NE,2025092104,NE,PIT,REG,3,PIT,away,NE,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254490,4081.0,2025_03_PIT_NE,2025092104,NE,PIT,REG,3,PIT,away,NE,...,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(pbp_all.columns.tolist())

pbp_all.info()

pbp_all.describe()

['play_id', 'game_id', 'old_game_id', 'home_team', 'away_team', 'season_type', 'week', 'posteam', 'posteam_type', 'defteam', 'side_of_field', 'yardline_100', 'game_date', 'quarter_seconds_remaining', 'half_seconds_remaining', 'game_seconds_remaining', 'game_half', 'quarter_end', 'drive', 'sp', 'qtr', 'down', 'goal_to_go', 'time', 'yrdln', 'ydstogo', 'ydsnet', 'desc', 'play_type', 'yards_gained', 'shotgun', 'no_huddle', 'qb_dropback', 'qb_kneel', 'qb_spike', 'qb_scramble', 'pass_length', 'pass_location', 'air_yards', 'yards_after_catch', 'run_location', 'run_gap', 'field_goal_result', 'kick_distance', 'extra_point_result', 'two_point_conv_result', 'home_timeouts_remaining', 'away_timeouts_remaining', 'timeout', 'timeout_team', 'td_team', 'td_player_name', 'td_player_id', 'posteam_timeouts_remaining', 'defteam_timeouts_remaining', 'total_home_score', 'total_away_score', 'posteam_score', 'defteam_score', 'score_differential', 'posteam_score_post', 'defteam_score_post', 'score_differential_post', 'no_score_prob', 'opp_fg_prob', 'opp_safety_prob', 'opp_td_prob', 'fg_prob', 'safety_prob', 'td_prob', 'extra_point_prob', 'two_point_conversion_prob', 'ep', 'epa', 'total_home_epa', 'total_away_epa', 'total_home_rush_epa', 'total_away_rush_epa', 'total_home_pass_epa', 'total_away_pass_epa', 'air_epa', 'yac_epa', 'comp_air_epa', 'comp_yac_epa', 'total_home_comp_air_epa', 'total_away_comp_air_epa', 'total_home_comp_yac_epa', 'total_away_comp_yac_epa', 'total_home_raw_air_epa', 'total_away_raw_air_epa', 'total_home_raw_yac_epa', 'total_away_raw_yac_epa', 'wp', 'def_wp', 'home_wp', 'away_wp', 'wpa', 'vegas_wpa', 'vegas_home_wpa', 'home_wp_post', 'away_wp_post', 'vegas_wp', 'vegas_home_wp', 'total_home_rush_wpa', 'total_away_rush_wpa', 'total_home_pass_wpa', 'total_away_pass_wpa', 'air_wpa', 'yac_wpa', 'comp_air_wpa', 'comp_yac_wpa', 'total_home_comp_air_wpa', 'total_away_comp_air_wpa', 'total_home_comp_yac_wpa', 'total_away_comp_yac_wpa', 'total_home_raw_air_wpa', 'total_away_raw_air_wpa', 'total_home_raw_yac_wpa', 'total_away_raw_yac_wpa', 'punt_blocked', 'first_down_rush', 'first_down_pass', 'first_down_penalty', 'third_down_converted', 'third_down_failed', 'fourth_down_converted', 'fourth_down_failed', 'incomplete_pass', 'touchback', 'interception', 'punt_inside_twenty', 'punt_in_endzone', 'punt_out_of_bounds', 'punt_downed', 'punt_fair_catch', 'kickoff_inside_twenty', 'kickoff_in_endzone', 'kickoff_out_of_bounds', 'kickoff_downed', 'kickoff_fair_catch', 'fumble_forced', 'fumble_not_forced', 'fumble_out_of_bounds', 'solo_tackle', 'safety', 'penalty', 'tackled_for_loss', 'fumble_lost', 'own_kickoff_recovery', 'own_kickoff_recovery_td', 'qb_hit', 'rush_attempt', 'pass_attempt', 'sack', 'touchdown', 'pass_touchdown', 'rush_touchdown', 'return_touchdown', 'extra_point_attempt', 'two_point_attempt', 'field_goal_attempt', 'kickoff_attempt', 'punt_attempt', 'fumble', 'complete_pass', 'assist_tackle', 'lateral_reception', 'lateral_rush', 'lateral_return', 'lateral_recovery', 'passer_player_id', 'passer_player_name', 'passing_yards', 'receiver_player_id', 'receiver_player_name', 'receiving_yards', 'rusher_player_id', 'rusher_player_name', 'rushing_yards', 'lateral_receiver_player_id', 'lateral_receiver_player_name', 'lateral_receiving_yards', 'lateral_rusher_player_id', 'lateral_rusher_player_name', 'lateral_rushing_yards', 'lateral_sack_player_id', 'lateral_sack_player_name', 'interception_player_id', 'interception_player_name', 'lateral_interception_player_id', 'lateral_interception_player_name', 'punt_returner_player_id', 'punt_returner_player_name', 'lateral_punt_returner_player_id', 'lateral_punt_returner_player_name', 'kickoff_returner_player_name', 'kickoff_returner_player_id', 'lateral_kickoff_returner_player_id', 'lateral_kickoff_returner_player_name', 'punter_player_id', 'punter_player_name', 'kicker_player_name', 'kicker_player_id', 'own_kickoff_recovery_player_id', 'own_kickoff_recovery_player_name', 'blocked_player_id', 'blocked_player_name', 'tackle_for_loss_1_player_id', 'tackle_for_loss_1_player_name', 'tackle_for_loss_2_player_id', 'tackle_for_loss_2_player_name', 'qb_hit_1_player_id', 'qb_hit_1_player_name', 'qb_hit_2_player_id', 'qb_hit_2_player_name', 'forced_fumble_player_1_team', 'forced_fumble_player_1_player_id', 'forced_fumble_player_1_player_name', 'forced_fumble_player_2_team', 'forced_fumble_player_2_player_id', 'forced_fumble_player_2_player_name', 'solo_tackle_1_team', 'solo_tackle_2_team', 'solo_tackle_1_player_id', 'solo_tackle_2_player_id', 'solo_tackle_1_player_name', 'solo_tackle_2_player_name', 'assist_tackle_1_player_id', 'assist_tackle_1_player_name', 'assist_tackle_1_team', 'assist_tackle_2_player_id', 'assist_tackle_2_player_name', 'assist_tackle_2_team', 'assist_tackle_3_player_id', 'assist_tackle_3_player_name', 'assist_tackle_3_team', 'assist_tackle_4_player_id', 'assist_tackle_4_player_name', 'assist_tackle_4_team', 'tackle_with_assist', 'tackle_with_assist_1_player_id', 'tackle_with_assist_1_player_name', 'tackle_with_assist_1_team', 'tackle_with_assist_2_player_id', 'tackle_with_assist_2_player_name', 'tackle_with_assist_2_team', 'pass_defense_1_player_id', 'pass_defense_1_player_name', 'pass_defense_2_player_id', 'pass_defense_2_player_name', 'fumbled_1_team', 'fumbled_1_player_id', 'fumbled_1_player_name', 'fumbled_2_player_id', 'fumbled_2_player_name', 'fumbled_2_team', 'fumble_recovery_1_team', 'fumble_recovery_1_yards', 'fumble_recovery_1_player_id', 'fumble_recovery_1_player_name', 'fumble_recovery_2_team', 'fumble_recovery_2_yards', 'fumble_recovery_2_player_id', 'fumble_recovery_2_player_name', 'sack_player_id', 'sack_player_name', 'half_sack_1_player_id', 'half_sack_1_player_name', 'half_sack_2_player_id', 'half_sack_2_player_name', 'return_team', 'return_yards', 'penalty_team', 'penalty_player_id', 'penalty_player_name', 'penalty_yards', 'replay_or_challenge', 'replay_or_challenge_result', 'penalty_type', 'defensive_two_point_attempt', 'defensive_two_point_conv', 'defensive_extra_point_attempt', 'defensive_extra_point_conv', 'safety_player_name', 'safety_player_id', 'season', 'cp', 'cpoe', 'series', 'series_success', 'series_result', 'order_sequence', 'start_time', 'time_of_day', 'stadium', 'weather', 'nfl_api_id', 'play_clock', 'play_deleted', 'play_type_nfl', 'special_teams_play', 'st_play_type', 'end_clock_time', 'end_yard_line', 'fixed_drive', 'fixed_drive_result', 'drive_real_start_time', 'drive_play_count', 'drive_time_of_possession', 'drive_first_downs', 'drive_inside20', 'drive_ended_with_score', 'drive_quarter_start', 'drive_quarter_end', 'drive_yards_penalized', 'drive_start_transition', 'drive_end_transition', 'drive_game_clock_start', 'drive_game_clock_end', 'drive_start_yard_line', 'drive_end_yard_line', 'drive_play_id_started', 'drive_play_id_ended', 'away_score', 'home_score', 'location', 'result', 'total', 'spread_line', 'total_line', 'div_game', 'roof', 'surface', 'temp', 'wind', 'home_coach', 'away_coach', 'stadium_id', 'game_stadium', 'aborted_play', 'success', 'passer', 'passer_jersey_number', 'rusher', 'rusher_jersey_number', 'receiver', 'receiver_jersey_number', 'pass', 'rush', 'first_down', 'special', 'play', 'passer_id', 'rusher_id', 'receiver_id', 'name', 'jersey_number', 'id', 'fantasy_player_name', 'fantasy_player_id', 'fantasy', 'fantasy_id', 'out_of_bounds', 'home_opening_kickoff', 'qb_epa', 'xyac_epa', 'xyac_mean_yardage', 'xyac_median_yardage', 'xyac_success', 'xyac_fd', 'xpass', 'pass_oe']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254491 entries, 0 to 254490
Columns: 372 entries, play_id to pass_oe
dtypes: float64(199), int32(8), object(165)
memory usage: 714.5+ MB

,play_id,week,yardline_100,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,quarter_end,drive,sp,qtr,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
count,254491.000000,254491.000000,236478.000000,254469.000000,254469.000000,254469.000000,254491.000000,251603.000000,254491.000000,254491.000000,...,254491.000000,254491.000000,251579.000000,88269.000000,88269.000000,88269.000000,88269.000000,88269.000000,194066.000000,188907.000000
mean,2135.603070,9.592771,48.170337,409.532808,805.170783,1704.530627,0.017494,11.435066,0.075146,2.567820,...,0.087190,0.518321,0.003514,0.729000,5.487222,3.661591,0.778599,0.579657,0.627600,-0.978426
std,1247.546807,5.636252,24.170877,282.834041,561.446635,1059.401692,0.131102,6.625263,0.263627,1.131032,...,0.282113,0.499665,1.244323,0.527470,2.523217,2.563125,0.251498,0.355355,0.240346,42.325828
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,-13.031218,-3.181688,0.303169,0.000000,0.017248,0.004220,0.010774,-99.512959
25%,1063.000000,4.000000,30.000000,144.000000,274.000000,781.000000,0.000000,6.000000,0.000000,2.000000,...,0.000000,0.000000,-0.556342,0.325380,3.745303,2.000000,0.560577,0.242718,0.456202,-42.308021
50%,2119.000000,9.000000,50.000000,390.000000,787.000000,1800.000000,0.000000,11.000000,0.000000,3.000000,...,0.000000,1.000000,0.000000,0.605176,4.623471,3.000000,0.983354,0.479413,0.598881,4.038936
75%,3182.000000,15.000000,69.000000,654.000000,1288.000000,2594.000000,0.000000,17.000000,0.000000,4.000000,...,0.000000,1.000000,0.528975,0.995861,6.870509,5.000000,1.000000,0.999163,0.856106,33.643401
max,5523.000000,22.000000,99.000000,900.000000,1800.000000,3600.000000,1.000000,35.000000,1.000000,5.000000,...,1.000000,1.000000,8.882384,9.585749,23.952005,36.000000,1.000000,1.000000,0.997902,97.995057

In [11]:
print(pbp_all['pass'].value_counts())
print(pbp_all['rush'].value_counts())

print( "Average yards gained:", pbp_all['yards_gained'].mean())

pass
0.0    137458
1.0    117033
Name: count, dtype: int64
rush
0.0    181841
1.0     72650
Name: count, dtype: int64
Average yards gained: 4.036386545769826

In [12]:
team_yards = pbp_all.groupby( "posteam")["yards_gained"].mean().sort_values(ascending=False)
print(team_yards)

team_plays = pbp_all["posteam"].value_counts()
print(team_plays)

posteam
SF     4.711782
BUF    4.665503
KC     4.636731
BAL    4.623308
DET    4.584442
GB     4.578760
TB     4.436849
MIN    4.345477
LA     4.331854
PHI    4.314957
SEA    4.304062
DAL    4.301642
MIA    4.281670
LAC    4.251376
IND    4.233542
ATL    4.203764
ARI    4.200274
LV     4.191657
CIN    4.173597
JAX    4.126162
NO     4.116773
WAS    4.035800
CLE    4.035055
HOU    4.033714
NE     4.023022
DEN    4.008229
TEN    4.001402
PIT    3.895282
CHI    3.874186
CAR    3.792388
NYG    3.748847
NYJ    3.742451
Name: yards_gained, dtype: float64
posteam
KC     8593
TB     8217
BUF    8214
PHI    8132
DAL    7950
LA     7819
BAL    7770
SF     7743
CIN    7723
WAS    7687
CLE    7667
PIT    7604
DET    7600
LAC    7597
GB     7477
MIN    7462
ARI    7437
NO     7342
IND    7328
HOU    7307
NYG    7291
TEN    7278
MIA    7274
JAX    7232
LV     7227
CHI    7204
DEN    7181
ATL    7150
SEA    7128
CAR    7057
NYJ    7010
NE     6988
Name: count, dtype: int64

In [14]:
team_yards = pbp_all.groupby( "posteam")["yards_gained"].mean().sort_values(ascending=False)
print( "Average yards gained per team:")
print(team_yards)

team_plays = pbp_all["posteam"].value_counts()
print( "\nTotal number of plays per team:")
print(team_plays)

Average yards gained per team:
posteam
SF     4.711782
BUF    4.665503
KC     4.636731
BAL    4.623308
DET    4.584442
GB     4.578760
TB     4.436849
MIN    4.345477
LA     4.331854
PHI    4.314957
SEA    4.304062
DAL    4.301642
MIA    4.281670
LAC    4.251376
IND    4.233542
ATL    4.203764
ARI    4.200274
LV     4.191657
CIN    4.173597
JAX    4.126162
NO     4.116773
WAS    4.035800
CLE    4.035055
HOU    4.033714
NE     4.023022
DEN    4.008229
TEN    4.001402
PIT    3.895282
CHI    3.874186
CAR    3.792388
NYG    3.748847
NYJ    3.742451
Name: yards_gained, dtype: float64

Total number of plays per team:
posteam
KC     8593
TB     8217
BUF    8214
PHI    8132
DAL    7950
LA     7819
BAL    7770
SF     7743
CIN    7723
WAS    7687
CLE    7667
PIT    7604
DET    7600
LAC    7597
GB     7477
MIN    7462
ARI    7437
NO     7342
IND    7328
HOU    7307
NYG    7291
TEN    7278
MIA    7274
JAX    7232
LV     7227
CHI    7204
DEN    7181
ATL    7150
SEA    7128
CAR    7057
NYJ    7010
NE     6988
Name: count, dtype: int64

In [15]:
season_yards = pbp_all.groupby( "season")["yards_gained"].mean()
print( "Average yards gained per season:")
print(season_yards)

season_plays = pbp_all["season"].value_counts().sort_index()
print( "\nTotal number of plays per season:")
print(season_plays)

Average yards gained per season:
season
2020    4.176599
2021    4.050558
2022    4.033520
2023    3.945493
2024    4.017259
2025    3.818772
Name: yards_gained, dtype: float64

Total number of plays per season:
season
2020    47705
2021    49922
2022    49434
2023    49665
2024    49492
2025     8273
Name: count, dtype: int64

In [18]:
play_type_yards = pbp_all.groupby( "play_type")["yards_gained"].mean().sort_values(ascending=False)
print("Average yards gained by play type: ")
print(play_type_yards)

play_type_counts = pbp_all["play_type"].value_counts()
print( "\nNumber of plays by type:")
print(play_type_counts)

Average yards gained by play type:
play_type
pass           6.192702
run            4.518202
no_play        0.001014
extra_point    0.000000
kickoff        0.000000
field_goal     0.000000
punt           0.000000
qb_spike       0.000000
qb_kneel      -1.091913
Name: yards_gained, dtype: float64

Number of plays by type:
play_type
pass           105676
run             76202
no_play         23906
kickoff         14923
punt            11295
extra_point      6728
field_goal       5681
qb_kneel         2263
qb_spike          382
Name: count, dtype: int64